# Generated by Django 3.2.19 on 2023-05-31 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('default_address_1', models.CharField(max_length=80)),
                ('default_address_2', models.CharField(blank=True, max_length=80, null=True)),
                ('default_address_3', models.CharField(blank=True, max_length=80, null=True)),
                ('default_email', models.EmailField(max_length=254)),
                ('default_eircode', models.CharField(blank=True, max_length=10, null=True)),
                ('default_town', models.CharField(blank=True, max_length=40, null=True)),
                ('default_county', models.CharField(blank=True, max_length=80, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
