# Generated by Django 3.2.19 on 2023-05-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(choices=[(0, '12:03'), (15, '12:18'), (30, '12:33'), (45, '12:48'), (60, '13:03'), (75, '13:18'), (90, '13:33'), (105, '13:48')], null=True),
        ),
    ]
