# Generated by Django 3.2.19 on 2023-05-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(choices=[(0, '13:00'), (15, '13:15'), (30, '13:30'), (45, '13:45'), (60, '14:00'), (75, '14:15')], null=True),
        ),
    ]
