# Generated by Django 3.2.19 on 2023-05-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(choices=[(0, '13:47'), (15, '14:02'), (30, '14:17'), (45, '14:32'), (60, '14:47'), (75, '15:02')], null=True),
        ),
    ]
