# Generated by Django 3.2.19 on 2023-06-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(choices=[(0, '14:46'), (15, '15:01'), (30, '15:16'), (45, '15:31'), (60, '15:46'), (75, '16:01')], null=True),
        ),
    ]
