# Generated by Django 3.2.19 on 2023-06-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_order_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(choices=[(0, '12:42'), (15, '12:57'), (30, '13:12'), (45, '13:27'), (60, '13:42'), (75, '13:57')], null=True),
        ),
    ]
