# Generated by Django 3.2.19 on 2023-06-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(choices=[(0, '13:18'), (15, '13:33'), (30, '13:48'), (45, '14:03'), (60, '14:18'), (75, '14:33')], null=True),
        ),
    ]
