# Generated by Django 3.2.19 on 2023-06-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20230615_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(choices=[(1, '1 hour'), (2, '2 hours'), (3, '3 hours')], null=True),
        ),
    ]
