# Generated by Django 3.2.19 on 2023-06-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_alter_order_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(choices=[(0, '13:33'), (15, '13:48'), (30, '14:03'), (45, '14:18'), (60, '14:33'), (75, '14:48'), (90, '15:03'), (105, '15:18'), (120, '15:33'), (135, '15:48'), (150, '16:03'), (165, '16:18'), (180, '16:33'), (195, '16:48')], null=True),
        ),
    ]
