# Generated by Django 3.2.19 on 2023-06-16 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_alter_order_delivery_time'),
    ]

    operations = [
        
    ]
