# Generated by Django 3.2.19 on 2023-06-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_alter_order_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(choices=[('Closed', 'Sorry, we are closed for delivery')]),
        ),
    ]
