# Generated by Django 3.2.19 on 2023-05-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_food_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('name',)},
        ),
    ]
