# Generated by Django 3.2.19 on 2023-05-14 13:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_food_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='contains',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Nuts', 'Nuts'), ('Dairy', 'Dairy'), ('Gluten', 'Gluten'), ('Soy', 'Soy'), ('Fish', 'Fish'), ('Shellfish', 'Shellfish')], max_length=36),
        ),
    ]
