# Generated by Django 3.2.19 on 2023-05-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_food_contains'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='is_vegan',
            new_name='is_vegetarian',
        ),
    ]
